apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ai-example
  region: us-east-1
  version: "1.27"

nodeGroups:
  - name: gpu
    labels: { nvidia.com/gpu: "true" }
    instanceType: g4dn.xlarge
    desiredCapacity: 1
    volumeSize: 35
  - name: cpu
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 20
